/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                'md-primary': '#6750A4',
                'md-on-primary': '#FFFFFF',
                'md-primary-container': '#EADDFF',
                'md-on-primary-container': '#21005D',
                'md-secondary': '#625B71',
                'md-on-secondary': '#FFFFFF',
                'md-secondary-container': '#E8DEF8',
                'md-on-secondary-container': '#1D192B',
                'md-tertiary': '#7D5260',
                'md-on-tertiary': '#FFFFFF',
                'md-tertiary-container': '#FFD8E4',
                'md-on-tertiary-container': '#31111D',
                'md-error': '#B3261E',
                'md-on-error': '#FFFFFF',
                'md-error-container': '#F9DEDC',
                'md-on-error-container': '#410E0B',
                'md-surface': '#FFFBFE',
                'md-on-surface': '#1C1B1F',
                'md-surface-variant': '#F3EDF7',
                'md-on-surface-variant': '#49454F',
                'md-outline': '#79747E',
                'md-outline-variant': '#CAC4D0',
                'md-inverse-surface': '#313033',
                'md-inverse-on-surface': '#F4EFF4',
                'md-inverse-primary': '#D0BCFF',
                'md-background': '#FFFBFE',
                'md-status-good': '#E8F5E9',
                'md-status-good-text': '#2E7D32',
                'md-status-warning': '#FFF8E1',
                'md-status-warning-text': '#F57F17',
                'md-status-critical': '#FFF3E0',
                'md-status-critical-text': '#E65100',
                'md-status-overdue': '#FFEBEE',
                'md-status-overdue-text': '#C62828',
                'md-status-unknown': '#F5F5F5',
                'md-status-unknown-text': '#616161',
                'md-status-replaced': '#FAFAFA',
                'md-status-replaced-text': '#757575',
            },
            fontFamily: {
                'md-display': ['system-ui', 'Segoe UI', 'Roboto', 'sans-serif'],
                'md-body': ['system-ui', 'Segoe UI', 'Roboto', 'sans-serif'],
            },
            fontSize: {
                'display-large': ['57px', { lineHeight: '64px', letterSpacing: '-0.25px', fontWeight: '400' }],
                'display-medium': ['45px', { lineHeight: '52px', letterSpacing: '0px', fontWeight: '400' }],
                'display-small': ['36px', { lineHeight: '44px', letterSpacing: '0px', fontWeight: '400' }],
                'headline-large': ['32px', { lineHeight: '40px', letterSpacing: '0px', fontWeight: '400' }],
                'headline-medium': ['28px', { lineHeight: '36px', letterSpacing: '0px', fontWeight: '400' }],
                'headline-small': ['24px', { lineHeight: '32px', letterSpacing: '0px', fontWeight: '400' }],
                'title-large': ['22px', { lineHeight: '28px', letterSpacing: '0px', fontWeight: '500' }],
                'title-medium': ['16px', { lineHeight: '24px', letterSpacing: '0.15px', fontWeight: '500' }],
                'title-small': ['14px', { lineHeight: '20px', letterSpacing: '0.1px', fontWeight: '500' }],
                'body-large': ['16px', { lineHeight: '24px', letterSpacing: '0.5px', fontWeight: '400' }],
                'body-medium': ['14px', { lineHeight: '20px', letterSpacing: '0.25px', fontWeight: '400' }],
                'body-small': ['12px', { lineHeight: '16px', letterSpacing: '0.4px', fontWeight: '400' }],
                'label-large': ['14px', { lineHeight: '20px', letterSpacing: '0.1px', fontWeight: '500' }],
                'label-medium': ['12px', { lineHeight: '16px', letterSpacing: '0.5px', fontWeight: '500' }],
                'label-small': ['11px', { lineHeight: '16px', letterSpacing: '0.5px', fontWeight: '500' }],
            },
            spacing: {
                'md-1': '8px',
                'md-2': '16px',
                'md-3': '24px',
                'md-4': '32px',
                'md-5': '40px',
                'md-6': '48px',
            },
            borderRadius: {
                'md-xs': '4px',
                'md-sm': '8px',
                'md-md': '12px',
                'md-lg': '16px',
                'md-xl': '28px',
                'md-full': '9999px',
            },
            boxShadow: {
                'md-0': '0 0 0 0 rgba(0,0,0,0)',
                'md-1': '0 1px 3px 1px rgba(0,0,0,0.15), 0 1px 2px 0 rgba(0,0,0,0.3)',
                'md-2': '0 2px 6px 2px rgba(0,0,0,0.15), 0 1px 2px 0 rgba(0,0,0,0.3)',
                'md-3': '0 4px 8px 3px rgba(0,0,0,0.15), 0 1px 3px 0 rgba(0,0,0,0.3)',
                'md-4': '0 6px 10px 4px rgba(0,0,0,0.15), 0 2px 3px 0 rgba(0,0,0,0.3)',
                'md-5': '0 8px 12px 6px rgba(0,0,0,0.15), 0 4px 4px 0 rgba(0,0,0,0.3)',
            },
            transitionDuration: {
                'md-1': '100ms',
                'md-2': '200ms',
                'md-3': '300ms',
                'md-4': '400ms',
                'md-5': '500ms',
            },
        },
    },
    plugins: [],
}
